### ISSUE TITLE
How to start this UI showcase

### ISSUE THREAD

**Issue by marcusaram** [mint-lang/mint-ui-website#2]
Hi,

I'm exploring mint-lang and looking for a mint UI library and found this. I know this is work in progress but really want to see how it works.

When I try to build or start it it will run into:
```
I was looking for the name of an environment variable but found 
"documentation(Ui.Button)," instead. 

The name of an environment variable must be uppercase 

Here is the relevant code snippet: 

┌──┬ source/Main.mint:56:26 ───────────────────────────────────────────────────┐
│52│   |> Map.set(                                                             │
│53│     "Controls",                                                           │
│54│     [                                                                     │
│55│       {                                                                   │
│56│         documentation = @documentation(Ui.Button),                        │
│57│         path = "/components/button",                                      │
│58│         name = "Ui.Button",                                               │
│59│         key = "button",                                                   │
│60│         description = "Buttons communicate actions that users can take.", │
└──┴───────────────────────────────────────────────────────────────────────────┘

```

are you running something special to get this running?

Thank you for your fantastic work, hope that Mint will fit.

**Comment by gdotdesign** [comment]
Thanks for taking in interest in this project :slightly_smiling_face: 

If you want to take a look a **very early** build (few weeks old) can be found here https://mint-lang-ui.netlify.app/examples/login-screen   

There a couple of things you need to do if you want to run this locally at this point:
- clone `mint-ui` and `mint-ui-showcase` into the a directory so `mint-ui` could be resolved relatively from `mint-ui-showcase`
- have a custom build of Mint from the `compile-time-reflection` branch (https://github.com/mint-lang/mint/tree/compile-time-reflection)

Also keep in mind that this project is very young, I hope to release something tangible in a month or so.

**Comment by marcusaram** [comment]
First of all: It looks really good, way beyond my expectations! :+1: :smile: 
The first step I already figured out myself, for the other people that read this, you also need `mint-color`
The last step was the missing link, thank you.

Can't wait to just bootstrap on mint-ui, it would be awesome for the Mint community to have a good looking UI components.

**Comment by gdotdesign** [comment]
> Can't wait to just bootstrap on mint-ui, it would be awesome for the Mint community to have a good looking UI components.

That's is my motivation at this point, I hope having a UI library out there will bring more people in :smile:

**Comment by gdotdesign** [comment]
With `0.10.0` you can just run this as a normal Mint application.

**Comment by gdotdesign** [comment]
Closing this since just tagged Mint UI as 1.0.0.
